name: CommitChecks

on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.1"
      - uses: actions/checkout@v2
      - name:
        run: xcodebuild -scheme ConcurrencyContinuationReproduce test -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.1'

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/VergeTests.xcresult
        if: success() || failure()
