name: CommitChecks

on: [push]

jobs:
  test-on-14:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.0"]
        destination:
          - "platform=iOS Simulator,OS=16.0,name=iPhone 14"
          - 'platform=iOS Simulator,OS=15.4,name=iPhone 8'
          - 'platform=iOS Simulator,OS=14.5,name=iPhone 8'
          - 'platform=iOS Simulator,OS=13.7,name=iPhone 8'
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v2
      - name: Create Simulators
        run: |
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-13-7;
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-14-5;
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-15-4;
      - name: Test
        run: xcodebuild -scheme ConcurrencyContinuationReproduce test  -resultBundlePath results/Tests.xcresult -destination "${{ matrix.destination }}" | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/Tests.xcresult
        if: success() || failure()

  test-on-14-1:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.1"]
        destination: 
          - 'platform=iOS Simulator,OS=16.1,name=iPhone 14'
          - 'platform=iOS Simulator,OS=15.4,name=iPhone 8'
          - 'platform=iOS Simulator,OS=14.5,name=iPhone 8'
          - 'platform=iOS Simulator,OS=13.7,name=iPhone 8'
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: ${{ matrix.xcode }}          
      - uses: actions/checkout@v2
      - name: Create Simulators
        run: |
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-13-7;
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-14-5;
          xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-15-4;      
      - name: Test      
        run: xcodebuild -scheme ConcurrencyContinuationReproduce test -resultBundlePath results/Tests.xcresult -destination "${{ matrix.destination }}" | xcpretty
        
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/Tests.xcresult
        if: success() || failure()        
